'use client'
import { useMemo, useState } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import Fuse from 'fuse.js'
import { Search, SlidersHorizontal, X } from 'lucide-react'
import type { Problem } from '@/lib/types'
import { ProblemCard } from './problem-card'

type Key = 'difficulty'|'pattern'|'algorithm'|'datastructure'|'company'|'status'|'confidence'|'tag'
const getValue=(p:Problem,k:Key):string[]=>{const v=k==='company'?p.companies:k==='tag'?p.tags:p[k==='datastructure'?'datastructure':k as keyof Problem] as unknown;return Array.isArray(v)?v.map(String):[String(v||'')]}
export function SearchableProblems({problems}:{problems:Problem[]}){
 const router=useRouter(),params=useSearchParams(),keys:Key[]=['difficulty','pattern','algorithm','datastructure','company','status','confidence','tag']
 const [q,setQ]=useState(params.get('q')||''),[filters,setFilters]=useState<Partial<Record<Key,string>>>(()=>Object.fromEntries(keys.map(k=>[k,params.get(k)||'']))),[due,setDue]=useState(params.get('due')==='true'),[fav,setFav]=useState(params.get('favorite')==='true')
 const updateUrl=(next:Partial<Record<Key,string>>=filters,nextQ=q,nextDue=due,nextFav=fav)=>{const s=new URLSearchParams();if(nextQ)s.set('q',nextQ);Object.entries(next).forEach(([k,v])=>v&&s.set(k,v));if(nextDue)s.set('due','true');if(nextFav)s.set('favorite','true');router.replace(`/problems${s.size?`?${s}`:''}`,{scroll:false})}
 const values=(k:Key)=>[...new Set(problems.flatMap(p=>getValue(p,k)).filter(Boolean))].sort()
 const results=useMemo(()=>{let list=q?new Fuse(problems,{keys:['title','body','pattern','companies','algorithm','datastructure','tags'],threshold:.35}).search(q).map(r=>r.item):problems;Object.entries(filters).forEach(([k,v])=>{if(v)list=list.filter(p=>getValue(p,k as Key).includes(v))});return list.filter(p=>(!due||!!p.revision&&new Date(p.revision)<=new Date())&&(!fav||p.favorite))},[problems,q,filters,due,fav])
 const active=q||Object.values(filters).some(Boolean)||due||fav
 return <><div className="panel sticky top-20 z-20 mb-6 p-3"><div className="flex flex-col gap-3 sm:flex-row"><label className="flex flex-1 items-center gap-2 rounded-xl bg-slate-100 px-3 dark:bg-slate-800"><Search className="size-4 text-slate-400"/><input value={q} onChange={e=>{setQ(e.target.value);updateUrl(filters,e.target.value)}} placeholder="Search titles, explanations, companies, tags…" className="h-10 w-full bg-transparent text-sm outline-none"/></label><div className="flex gap-2"><button onClick={()=>{setDue(!due);updateUrl(filters,q,!due,fav)}} className={`chip ${due?'border-amber-500 bg-amber-50 text-amber-700':''}`}>Revision due</button><button onClick={()=>{setFav(!fav);updateUrl(filters,q,due,!fav)}} className={`chip ${fav?'border-rose-500 bg-rose-50 text-rose-700':''}`}>Favorite</button></div></div><div className="mt-3 flex flex-wrap items-center gap-2"><SlidersHorizontal className="size-4 text-slate-400"/>{keys.map(k=><select key={k} value={filters[k]||''} onChange={e=>{const n={...filters,[k]:e.target.value};setFilters(n);updateUrl(n)}} className="h-8 max-w-40 rounded-lg border bg-transparent px-2 text-xs"><option value="">{k==='datastructure'?'Data structure':k[0].toUpperCase()+k.slice(1)}</option>{values(k).map(v=><option key={v}>{v}</option>)}</select>)}{active&&<button onClick={()=>{setQ('');setFilters({});setDue(false);setFav(false);router.replace('/problems',{scroll:false})}} className="grid size-7 place-items-center"><X className="size-4"/></button>}</div></div><p className="mb-4 text-sm text-slate-500">{results.length} problem{results.length!==1?'s':''} found</p><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{results.map(p=><ProblemCard key={p.slug} problem={p}/>)}</div>{!results.length&&<div className="panel p-10 text-center text-slate-500">No notes match these filters.</div>}</>}